#include "TCanvas.h"
#include "TGraph.h"
#include "TLegend.h"
#include "TMultiGraph.h"

#include <cmath>
#include <gsl/gsl_sf_bessel.h>
#include <iostream>
#include <vector>

// Constant values
const double hbar = 6.582119569e-22; // Planck's constant in MeV·s
const double c = 3.0e23;
const double u_to_kg = 1.66053906660e-27; // Atomic mass to kg
const double MeV_to_J = 1.60218e-13;      // MeV to J
const double mass_C15_u = 14.003241989;   // 15C mass in atomic mass
const double mass_neutron_u = 1.008665;   // neutron mass in atomic mass
const double r = 4.2626779;               // Interaction radius in fm
const double Sp = 1.2181;

double calculatePenetrability(double E, double L)
{
   double mu = (mass_C15_u * mass_neutron_u) / (mass_C15_u + mass_neutron_u);
   double k = sqrt(2 * mu * 931.4936 * E) / (hbar * c);
   double x = k * r;
   double J = gsl_sf_bessel_Jn(L + 0.5, x);
   double Y = gsl_sf_bessel_Yn(L + 0.5, x);
   double T = k / (J * J + Y * Y);
   return T;
}

void generateDataFile(const std::vector<double> &energies, const std::vector<double> &penetrabilities, int L)
{
   std::string filename = "penetrabilities_neutron_15C_L_" + std::to_string(L) + ".C";
   std::ofstream outfile(filename);

   outfile << "// File generated by Calculator_Penetrability_neutron.C\n";
   outfile << "// Contains penetrability data for L = " << L << "\n\n";

   outfile << "double energies_neutron_15C_L_" << L << "[" << energies.size() << "] = {";
   for (size_t i = 0; i < energies.size(); ++i) {
      outfile << energies[i];
      if (i < energies.size() - 1)
         outfile << ", ";
   }
   outfile << "};\n\n";

   outfile << "double T" << L << "_neutron_15C_values"
           << "[" << penetrabilities.size() << "] = {";
   for (size_t i = 0; i < penetrabilities.size(); ++i) {
      outfile << penetrabilities[i];
      if (i < penetrabilities.size() - 1)
         outfile << ", ";
   }
   outfile << "};\n\n";

   outfile << "int num_points_L_" << L << " = " << energies.size() << ";\n";

   outfile.close();
   std::cout << "Data file generated: " << filename << std::endl;
}

void Calculator_Penetrability_neutron_15C()
{
   std::vector<int> L_values = {0, 1, 2, 3};
   double E_start = 1.22;
   double E_end = 9.00;
   double E_step = 0.000778; // to get 10000 points in the BW

   // Canvas for Penetrability
   TCanvas *c1 = new TCanvas("c1", "Penetrability vs Neutron Energy", 800, 600);
   c1->SetLogy(); // Set logarithmic scale on the y-axis
   TLegend *legend = new TLegend(0.7, 0.7, 0.9, 0.9);
   double y_min = 1e-20; // Adjust this to set the lower limit of the y-axis
   double y_max = 1;     // Upper limit of the y-axis

   for (size_t i = 0; i < L_values.size(); ++i) {
      int L = L_values[i];
      std::vector<double> neutron_energies;
      std::vector<double> penetrabilities;

      for (double E = E_start; E <= E_end; E += E_step) {
         double neutron_energy_MeV = E - Sp;
         double neutron_energy_keV = neutron_energy_MeV * 1000.0; // Convert to keV
         double T = calculatePenetrability(neutron_energy_MeV, L);

         if (T >= 0) {
            neutron_energies.push_back(neutron_energy_keV);
            penetrabilities.push_back(T);
            std::cout << "Penetrability for L = " << L << ", E = " << E << ": " << T << "\n";
         }
      }
      generateDataFile(neutron_energies, penetrabilities, L);

      // Penetrability Graph
      TGraph *gr = new TGraph(neutron_energies.size(), &neutron_energies[0], &penetrabilities[0]);
      gr->SetLineColor(i + 1);
      gr->SetLineWidth(2);
      gr->SetTitle("Penetrability vs. Energy");

      if (neutron_energies.size() > 0) { // Only draw if there is data
         if (i == 0) {
            c1->cd();
            gr->Draw("AL");
            gr->GetXaxis()->SetTitle("E_{n} in CM (keV)"); // x-axis in keV
            gr->GetYaxis()->SetTitle("Penetrability");
            gr->GetYaxis()->SetRangeUser(y_min, y_max); // Set y-axis limits

         } else {
            c1->cd();
            gr->Draw("L same");
         }

         legend->AddEntry(gr, Form("L = %d", L), "l");

         c1->cd();
         legend->Draw();
         c1->Update();
      }
   }
}
