// root -l -e 'gSystem->AddLinkedLibs("-lgsl -lgslcblas"); gROOT->ProcessLine(".x
// Calculator_Penetrability_neutron_15C.C+")'

#include "TAxis.h"
#include "TCanvas.h"
#include "TGraph.h"
#include "TLegend.h"
#include "TMultiGraph.h"

#include <cmath>
#include <fstream>
#include <gsl/gsl_sf_bessel.h>
#include <iostream>
#include <vector>

// Constant values
const double hbarc = 197.3269804; // MeV·fm
const int A = 15;
const double mass_C14_u = 14.003242;           // 14C masa en amu
const double mass_n_u = 1.008665;              // neutrón en amu
const double r = 1.2 * std::pow(A, 1.0 / 3.0); // Interaction radius in fm
const double Sn = 1.2181;
const double uma_to_MeV = 931.49410242; // MeV/u (CODATA 2018)

double calculatePenetrability(double E, int L)
{
   double mu = (mass_C14_u * mass_n_u) / (mass_C14_u + mass_n_u);
   double k = sqrt(2 * mu * uma_to_MeV * E) / hbarc; // fm⁻1
   double x = k * r;
   double J = gsl_sf_bessel_jl(L, x);
   double Y = gsl_sf_bessel_yl(L, x);
   double T = 1 / (x * (J * J + Y * Y));
   return T;
}

/*double calculatePenetrability(double E, double L)
{
   double mu = (mass_C14_u * mass_n_u) / (mass_C14_u + mass_n_u);
   double k = sqrt(2 * mu * uma_to_MeV * E) / hbarc; // fm⁻1
   double x = k * r;
   double J = gsl_sf_bessel_Jn(L + 0.5, x);
   double Y = gsl_sf_bessel_Yn(L + 0.5, x); //aqui se espera que el orden n sea entero, si L+0.5=2.5 ->2: está mal.
   double T = k / (J * J + Y * Y);
   return T;
}*/

std::vector<double> buildNonUniformGrid(double Sn, double E_end)
{
   std::vector<double> energies;

   double fine_step = 0.0005;
   double fine_end = Sn + 0.5;

   double mid_step = 0.002;
   double mid_end = Sn + 2.0;

   double coarse_step = 0.01;

   // NO push_back(Sn) -- evita x=0 exacto en Bessel
   for (double E = Sn + fine_step; E <= fine_end; E += fine_step)
      energies.push_back(E);

   for (double E = fine_end + mid_step; E <= mid_end; E += mid_step)
      energies.push_back(E);

   for (double E = mid_end + coarse_step; E <= E_end; E += coarse_step)
      energies.push_back(E);

   return energies;
}

void generateDataFile(const std::vector<double> &energies, const std::vector<double> &penetrabilities, int L)
{
   std::string filename = "penetrabilities_neutron_15C_L_long" + std::to_string(L) + ".C";
   std::ofstream outfile(filename);

   outfile << "// File generated by Calculator_Penetrability_neutron.C\n";
   outfile << "// Contains penetrability data for L = " << L << "\n\n";

   outfile << "double energies_neutron_15C_L_" << L << "[" << energies.size() << "] = {";
   for (size_t i = 0; i < energies.size(); ++i) {
      outfile << energies[i];
      if (i < energies.size() - 1)
         outfile << ", ";
   }
   outfile << "};\n\n";

   outfile << "double T" << L << "_neutron_15C_values"
           << "[" << penetrabilities.size() << "] = {";
   for (size_t i = 0; i < penetrabilities.size(); ++i) {
      outfile << penetrabilities[i];
      if (i < penetrabilities.size() - 1)
         outfile << ", ";
   }
   outfile << "};\n\n";

   outfile << "int num_points_L_" << L << " = " << energies.size() << ";\n";

   outfile.close();
   std::cout << "Data file generated: " << filename << std::endl;
}

void Calculator_Penetrability_neutron_15C()
{
   std::vector<int> L_values = {0, 1, 2, 3};
   // double E_step = 0.000778;     // to get 10000 points in the BW
   // double E_step = 0.001;
   double E_step = 0.0005;
   double E_start = Sn + E_step; // Start from the neutron separation energy
   double E_end = 9.00;

   // Canvas for Penetrability
   TCanvas *c1 = new TCanvas("c1", "Penetrability vs Neutron Energy", 800, 600);
   c1->SetLogy(); // Set logarithmic scale on the y-axis
   TLegend *legend = new TLegend(0.7, 0.7, 0.9, 0.9);
   double y_min = 1e-20; // Adjust this to set the lower limit of the y-axis
   double y_max = 1;     // Upper limit of the y-axis

   for (size_t i = 0; i < L_values.size(); ++i) {
      int L = L_values[i];

      // std::vector<double> grid_E_abs = buildNonUniformGrid(Sn, E_end); // energías absolutas
      std::vector<double> neutron_energies; // vector limpio, vacío
      std::vector<double> penetrabilities;

      /*for (double E_abs : grid_E_abs) {
         double neutron_energy_MeV = E_abs - Sn;
         double T = calculatePenetrability(neutron_energy_MeV, L);

         if (T >= 0) {
            neutron_energies.push_back(neutron_energy_MeV);
            penetrabilities.push_back(T);
         }
      }*/
      for (double E_abs = E_start; E_abs <= E_end; E_abs += E_step) {
         double neutron_energy_MeV = E_abs - Sn;
         double T = calculatePenetrability(neutron_energy_MeV, L);

         if (T >= 0) {
            neutron_energies.push_back(neutron_energy_MeV);
            penetrabilities.push_back(T);
         }
      }
      generateDataFile(neutron_energies, penetrabilities, L);

      // Penetrability Graph
      TGraph *gr = new TGraph(neutron_energies.size(), &neutron_energies[0], &penetrabilities[0]);
      gr->SetLineColor(i + 1);
      gr->SetLineWidth(2);
      gr->SetTitle("Penetrability vs. Energy");

      if (neutron_energies.size() > 0) { // Only draw if there is data
         if (i == 0) {
            c1->cd();
            gr->Draw("AL");
            gr->GetXaxis()->SetTitle("E_{n} in CM (MeV)"); // x-axis in keV
            gr->GetYaxis()->SetTitle("Penetrability");
            gr->GetYaxis()->SetRangeUser(y_min, y_max); // Set y-axis limits

         } else {
            c1->cd();
            gr->Draw("L same");
         }

         legend->AddEntry(gr, Form("L = %d", L), "l");

         c1->cd();
         legend->Draw();
         c1->Update();
      }
   }
}
